### ISSUE TITLE
Feat: Movie player

### ISSUE THREAD

**Issue by Zorlin** [riffcc/ceramic-riff-web#19]
I would like if if we had a movie player that looked like this:

![Image](https://user-images.githubusercontent.com/1369772/212397343-d5673b00-cdbf-41ba-aa80-d3754c10aa80.png)

Icons are from font-awesome

Color of the slider is #5558DD for the bits already played, #343434 for the bits yet to play. It's important it's exactly these colours for now :)

When you hover over a movie, it should show a play icon
When you click it it should take you to this player and play the movie
When you move the mouse, it should bring up the player controls as seen in this screenshot, otherwise it should hide them (after a few seconds) so you can watch the movie uninterrupted

**Comment by enok1111** [comment]
![Image](https://github.com/riffcc/ceramic-riff-web/assets/28759552/a95c2a76-ea97-4fd5-bb1c-d104c22378aa)

😄

**Comment by Zorlin** [comment]
> Member

Excellent! your own private library, obviously ;)

This has since been reimplemented in Orbiter and is happily complete!
